INSERT INTO `paises` (`id_pais`, `nombre`, `codigo`) VALUES
(1, 'Afghanistan', 'AF'),
(2, 'Albania', 'AL'),
(3, 'Algeria', 'DZ'),
(4, 'Andorra', 'AD'),
(5, 'Angola', 'AO'),
(6, 'Argentina', 'AR'),
(7, 'Armenia', 'AM'),
(8, 'Australia', 'AU'),
(9, 'Austria', 'AT'),
(10, 'Azerbaijan', 'AZ'),
(11, 'Bahamas', 'BS'),
(12, 'Bahrain', 'BH'),
(13, 'Bangladesh', 'BD'),
(14, 'Barbados', 'BB'),
(15, 'Belarus', 'BY'),
(16, 'Belgium', 'BE'),
(17, 'Belize', 'BZ'),
(18, 'Benin', 'BJ'),
(19, 'Bhutan', 'BT'),
(20, 'Bolivia', 'BO'),
(21, 'Bosnia and Herzegovina', 'BA'),
(22, 'Botswana', 'BW'),
(23, 'Brazil', 'BR'),
(24, 'Brunei', 'BN'),
(25, 'Bulgaria', 'BG'),
(26, 'Burkina Faso', 'BF'),
(27, 'Burundi', 'BI'),
(28, 'Cabo Verde', 'CV'),
(29, 'Cambodia', 'KH'),
(30, 'Cameroon', 'CM'),
(31, 'Canada', 'CA'),
(32, 'Central African Republic', 'CF'),
(33, 'Chad', 'TD'),
(34, 'Chile', 'CL'),
(35, 'China', 'CN'),
(36, 'Colombia', 'CO'),
(37, 'Comoros', 'KM'),
(38, 'Congo', 'CG'),
(39, 'Costa Rica', 'CR'),
(40, 'Croatia', 'HR'),
(41, 'Cuba', 'CU'),
(42, 'Cyprus', 'CY'),
(43, 'Czech Republic', 'CZ'),
(44, 'Denmark', 'DK'),
(45, 'Djibouti', 'DJ'),
(46, 'Dominica', 'DM'),
(47, 'Dominican Republic', 'DO'),
(48, 'Ecuador', 'EC'),
(49, 'Egypt', 'EG'),
(50, 'El Salvador', 'SV'),
(51, 'Equatorial Guinea', 'GQ'),
(52, 'Eritrea', 'ER'),
(53, 'Estonia', 'EE'),
(54, 'Eswatini', 'SZ'),
(55, 'Ethiopia', 'ET'),
(56, 'Fiji', 'FJ'),
(57, 'Finland', 'FI'),
(58, 'France', 'FR'),
(59, 'Gabon', 'GA'),
(60, 'Gambia', 'GM'),
(61, 'Georgia', 'GE'),
(62, 'Germany', 'DE'),
(63, 'Ghana', 'GH'),
(64, 'Greece', 'GR'),
(65, 'Grenada', 'GD'),
(66, 'Guatemala', 'GT'),
(67, 'Guinea', 'GN'),
(68, 'Guinea-Bissau', 'GW'),
(69, 'Guyana', 'GY'),
(70, 'Haiti', 'HT'),
(71, 'Honduras', 'HN'),
(72, 'Hungary', 'HU'),
(73, 'Iceland', 'IS'),
(74, 'India', 'IN'),
(75, 'Indonesia', 'ID'),
(76, 'Iran', 'IR'),
(77, 'Iraq', 'IQ'),
(78, 'Ireland', 'IE'),
(79, 'Israel', 'IL'),
(80, 'Italy', 'IT'),
(81, 'Jamaica', 'JM'),
(82, 'Japan', 'JP'),
(83, 'Jordan', 'JO'),
(84, 'Kazakhstan', 'KZ'),
(85, 'Kenya', 'KE'),
(86, 'Kiribati', 'KI'),
(87, 'Kuwait', 'KW'),
(88, 'Kyrgyzstan', 'KG'),
(89, 'Laos', 'LA'),
(90, 'Latvia', 'LV'),
(91, 'Lebanon', 'LB'),
(92, 'Lesotho', 'LS'),
(93, 'Liberia', 'LR'),
(94, 'Libya', 'LY'),
(95, 'Liechtenstein', 'LI'),
(96, 'Lithuania', 'LT'),
(97, 'Luxembourg', 'LU'),
(98, 'Madagascar', 'MG'),
(99, 'Malawi', 'MW'),
(100, 'Malaysia', 'MY'),
(101, 'Maldives', 'MV'),
(102, 'Mali', 'ML'),
(103, 'Malta', 'MT'),
(104, 'Marshall Islands', 'MH'),
(105, 'Mauritania', 'MR'),
(106, 'Mauritius', 'MU'),
(107, 'Mexico', 'MX'),
(108, 'Micronesia', 'FM'),
(109, 'Moldova', 'MD'),
(110, 'Monaco', 'MC'),
(111, 'Mongolia', 'MN'),
(112, 'Montenegro', 'ME'),
(113, 'Morocco', 'MA'),
(114, 'Mozambique', 'MZ'),
(115, 'Myanmar', 'MM'),
(116, 'Namibia', 'NA'),
(117, 'Nauru', 'NR'),
(118, 'Nepal', 'NP'),
(119, 'Netherlands', 'NL'),
(120, 'New Zealand', 'NZ'),
(121, 'Nicaragua', 'NI'),
(122, 'Niger', 'NE'),
(123, 'Nigeria', 'NG'),
(124, 'North Korea', 'KP'),
(125, 'North Macedonia', 'MK'),
(126, 'Norway', 'NO'),
(127, 'Oman', 'OM'),
(128, 'Pakistan', 'PK'),
(129, 'Palau', 'PW'),
(130, 'Panama', 'PA'),
(131, 'Papua New Guinea', 'PG'),
(132, 'Paraguay', 'PY'),
(133, 'Peru', 'PE'),
(134, 'Philippines', 'PH'),
(135, 'Poland', 'PL'),
(136, 'Portugal', 'PT'),
(137, 'Qatar', 'QA'),
(138, 'Romania', 'RO'),
(139, 'Russia', 'RU'),
(140, 'Rwanda', 'RW'),
(141, 'Saint Kitts and Nevis', 'KN'),
(142, 'Saint Lucia', 'LC'),
(143, 'Saint Vincent and the Grenadines', 'VC'),
(144, 'Samoa', 'WS'),
(145, 'San Marino', 'SM'),
(146, 'Sao Tome and Principe', 'ST'),
(147, 'Saudi Arabia', 'SA'),
(148, 'Senegal', 'SN'),
(149, 'Serbia', 'RS'),
(150, 'Seychelles', 'SC'),
(151, 'Sierra Leone', 'SL'),
(152, 'Singapore', 'SG'),
(153, 'Slovakia', 'SK'),
(154, 'Slovenia', 'SI'),
(155, 'Solomon Islands', 'SB'),
(156, 'Somalia', 'SO'),
(157, 'South Africa', 'ZA'),
(158, 'South Korea', 'KR'),
(159, 'South Sudan', 'SS'),
(160, 'Spain', 'ES'),
(161, 'Sri Lanka', 'LK'),
(162, 'Sudan', 'SD'),
(163, 'Suriname', 'SR'),
(164, 'Sweden', 'SE'),
(165, 'Switzerland', 'CH'),
(166, 'Syria', 'SY'),
(167, 'Taiwan', 'TW'),
(168, 'Tajikistan', 'TJ'),
(169, 'Tanzania', 'TZ'),
(170, 'Thailand', 'TH'),
(171, 'Timor-Leste', 'TL'),
(172, 'Togo', 'TG'),
(173, 'Tonga', 'TO'),
(174, 'Trinidad and Tobago', 'TT'),
(175, 'Tunisia', 'TN'),
(176, 'Turkey', 'TR'),
(177, 'Turkmenistan', 'TM'),
(178, 'Tuvalu', 'TV'),
(179, 'Uganda', 'UG'),
(180, 'Ukraine', 'UA'),
(181, 'United Arab Emirates', 'AE'),
(182, 'United Kingdom', 'GB'),
(183, 'United States', 'US'),
(184, 'Uruguay', 'UY'),
(185, 'Uzbekistan', 'UZ'),
(186, 'Vanuatu', 'VU'),
(187, 'Vatican City', 'VA'),
(188, 'Venezuela', 'VE'),
(189, 'Vietnam', 'VN'),
(190, 'Yemen', 'YE'),
(191, 'Zambia', 'ZM'),
(192, 'Zimbabwe', 'ZW');