-- MySQL Script generated by MySQL Workbench
-- Mon Sep 23 15:03:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_touristtrek
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_touristtrek
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_touristtrek` DEFAULT CHARACTER SET utf8mb4 ;
USE `bd_touristtrek` ;

-- -----------------------------------------------------
-- Table `bd_touristtrek`.`tipo_actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_touristtrek`.`tipo_actividad` (
  `id_tipoactividad` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipoactividad`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_touristtrek`.`actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_touristtrek`.`actividades` (
  `id_actividad` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `id_tipoactividad` INT(11) NOT NULL,
  PRIMARY KEY (`id_actividad`),
  INDEX `fk_actividades_tipo_actividad1_idx` (`id_tipoactividad` ASC) ,
  CONSTRAINT `fk_actividades_tipo_actividad1`
    FOREIGN KEY (`id_tipoactividad`)
    REFERENCES `bd_touristtrek`.`tipo_actividad` (`id_tipoactividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_touristtrek`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_touristtrek`.`proveedores` (
  `id_proveedor` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_empresa` VARCHAR(60) NULL DEFAULT NULL,
  `nombre_representante` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(60) NULL DEFAULT NULL,
  `telefono_principal` VARCHAR(10) NULL DEFAULT NULL,
  `telefono_secundario` VARCHAR(10) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_touristtrek`.`actividades_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_touristtrek`.`actividades_proveedor` (
  `idactividades_proveedor` INT(11) NOT NULL AUTO_INCREMENT,
  `tarifa_adultos` DECIMAL(10,2) NULL DEFAULT NULL,
  `tarifa_ninos` DECIMAL(10,2) NULL DEFAULT NULL,
  `tarifa_extranjero` DECIMAL(10,2) NULL DEFAULT NULL,
  `id_proveedor` INT(11) NOT NULL,
  `id_actividad` INT(11) NOT NULL,
  PRIMARY KEY (`idactividades_proveedor`),
  INDEX `fk_actividades_proveedor_proveedores_idx` (`id_proveedor` ASC) ,
  INDEX `fk_actividades_proveedor_actividades1_idx` (`id_actividad` ASC) ,
  CONSTRAINT `fk_actividades_proveedor_actividades1`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `bd_touristtrek`.`actividades` (`id_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividades_proveedor_proveedores`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `bd_touristtrek`.`proveedores` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_touristtrek`.`paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_touristtrek`.`paises` (
  `id_pais` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `codigo` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB
AUTO_INCREMENT = 193
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_touristtrek`.`tipo_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_touristtrek`.`tipo_cliente` (
  `id_tipocliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipocliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_touristtrek`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_touristtrek`.`clientes` (
  `id_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(13) NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `genero` CHAR(1) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `clave` VARCHAR(45) NULL DEFAULT NULL,
  `token` INT(11) NULL DEFAULT NULL,
  `id_tipocliente` INT(11) NOT NULL,
  `estado` INT(11) NULL DEFAULT NULL COMMENT '1 = ACTIVO\\n0 = INACTIVO',
  `id_pais` INT(11) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_clientes_tipo_cliente1_idx` (`id_tipocliente` ASC) ,
  INDEX `fk_clientes_paises1` (`id_pais` ASC) ,
  CONSTRAINT `fk_clientes_paises1`
    FOREIGN KEY (`id_pais`)
    REFERENCES `bd_touristtrek`.`paises` (`id_pais`),
  CONSTRAINT `fk_clientes_tipo_cliente1`
    FOREIGN KEY (`id_tipocliente`)
    REFERENCES `bd_touristtrek`.`tipo_cliente` (`id_tipocliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_touristtrek`.`medio_contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_touristtrek`.`medio_contacto` (
  `id_mediocontacto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_mediocontacto`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_touristtrek`.`contactos_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_touristtrek`.`contactos_cliente` (
  `id _contactoscliente` INT(11) NOT NULL AUTO_INCREMENT,
  `id_mediocontacto` INT(11) NOT NULL,
  `id_cliente` INT(11) NOT NULL,
  PRIMARY KEY (`id _contactoscliente`),
  INDEX `fk_contactos_cliente_medio_contacto1_idx` (`id_mediocontacto` ASC) ,
  INDEX `fk_contactos_cliente_clientes1_idx` (`id_cliente` ASC) ,
  CONSTRAINT `fk_contactos_cliente_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `bd_touristtrek`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contactos_cliente_medio_contacto1`
    FOREIGN KEY (`id_mediocontacto`)
    REFERENCES `bd_touristtrek`.`medio_contacto` (`id_mediocontacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_touristtrek`.`estados_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_touristtrek`.`estados_reserva` (
  `id_estadosreserva` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estadosreserva`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_touristtrek`.`metodos_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_touristtrek`.`metodos_pago` (
  `id_metodospago` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_metodospago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_touristtrek`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_touristtrek`.`reservas` (
  `id_reserva` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_registro` DATETIME NULL DEFAULT NULL,
  `fecha_reserva` DATETIME NULL DEFAULT NULL,
  `id_cliente` INT(11) NOT NULL,
  `estado_reserva` VARCHAR(45) NULL DEFAULT NULL,
  `id_estadosreserva` INT(11) NOT NULL,
  `factura` VARCHAR(20) NULL DEFAULT NULL,
  `id_metodospago` INT(11) NOT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `fk_reservas_clientes1_idx` (`id_cliente` ASC) ,
  INDEX `fk_reservas_estados_reserva1_idx` (`id_estadosreserva` ASC) ,
  INDEX `fk_reservas_metodos_pago1_idx` (`id_metodospago` ASC) ,
  CONSTRAINT `fk_reservas_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `bd_touristtrek`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_estados_reserva1`
    FOREIGN KEY (`id_estadosreserva`)
    REFERENCES `bd_touristtrek`.`estados_reserva` (`id_estadosreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_metodos_pago1`
    FOREIGN KEY (`id_metodospago`)
    REFERENCES `bd_touristtrek`.`metodos_pago` (`id_metodospago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_touristtrek`.`detalle_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_touristtrek`.`detalle_reserva` (
  `id_detalle_reserva` INT(11) NOT NULL AUTO_INCREMENT,
  `detalle_reservacol` VARCHAR(45) NULL DEFAULT NULL,
  `idactividades_proveedor` INT(11) NOT NULL,
  `cantidad_adultos` INT(11) NULL DEFAULT NULL,
  `cantidad_ninos` INT(11) NULL DEFAULT NULL,
  `transporte` INT(11) NULL DEFAULT NULL COMMENT '1 = SI\\n0 = NO',
  `id_reserva` INT(11) NOT NULL,
  `total_adulto` DECIMAL(10,2) NULL DEFAULT NULL,
  `total_niño` DECIMAL(10,2) NULL DEFAULT NULL,
  `total_transporte` DECIMAL(10,2) NULL DEFAULT NULL,
  `estado` INT(11) NULL DEFAULT NULL COMMENT '1 = ACTIVO\\n0= INACTIVO',
  PRIMARY KEY (`id_detalle_reserva`),
  INDEX `fk_detalle_reserva_actividades_proveedor1_idx` (`idactividades_proveedor` ASC) ,
  INDEX `fk_detalle_reserva_reservas1_idx` (`id_reserva` ASC) ,
  CONSTRAINT `fk_detalle_reserva_actividades_proveedor1`
    FOREIGN KEY (`idactividades_proveedor`)
    REFERENCES `bd_touristtrek`.`actividades_proveedor` (`idactividades_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_reserva_reservas1`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `bd_touristtrek`.`reservas` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_touristtrek`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_touristtrek`.`roles` (
  `id_rol` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_touristtrek`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_touristtrek`.`empleados` (
  `id_empleado` INT(11) NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `clave` VARCHAR(90) NULL DEFAULT NULL,
  `id_rol` INT(11) NOT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `fk_empleados_roles1_idx` (`id_rol` ASC) ,
  CONSTRAINT `fk_empleados_roles1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `bd_touristtrek`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_touristtrek`.`porcentaje_ganancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_touristtrek`.`porcentaje_ganancia` (
  `id_porcentajeganancia` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `valor` INT(11) NULL DEFAULT NULL,
  `estado` INT(11) NULL DEFAULT NULL COMMENT '1 = ACTIVO\\n0 = INACTIVO',
  PRIMARY KEY (`id_porcentajeganancia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_touristtrek`.`preferencias_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_touristtrek`.`preferencias_cliente` (
  `id_preferenciacliente` INT(11) NOT NULL AUTO_INCREMENT,
  `id_cliente` INT(11) NOT NULL,
  `id_tipoactividad` INT(11) NOT NULL,
  PRIMARY KEY (`id_preferenciacliente`),
  INDEX `fk_preferencias_cliente_clientes1_idx` (`id_cliente` ASC) ,
  INDEX `fk_preferencias_cliente_tipo_actividad1_idx` (`id_tipoactividad` ASC) ,
  CONSTRAINT `fk_preferencias_cliente_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `bd_touristtrek`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preferencias_cliente_tipo_actividad1`
    FOREIGN KEY (`id_tipoactividad`)
    REFERENCES `bd_touristtrek`.`tipo_actividad` (`id_tipoactividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
